[package]
name = "util"
version = "0.1.0"
authors = ["Johnny Bergström <johnny@klaudify.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
env_logger = "0.7"
log = "0.4"
chrono = "0.4"
